### ISSUE TITLE
Creating new collectionFS doc from S3 key

### ISSUE THREAD

**Issue by yogiben** [CollectionFS/Meteor-cfs-s3#28]
I need to use elastic transcoder to convert .mov to .mp4.

I upload the .mov to S3, convert it, get the key of the new file.

How can I insert a file into my FS.collection?

**Comment by aldeed** [comment]
Trying to centralize and close issues. Please post in https://github.com/CollectionFS/Meteor-CollectionFS repo if this is still an issue.

**Comment by raix** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/issues/325
