### ISSUE TITLE
How do I insert a file into a specific directory in the bucket from a string?

### ISSUE THREAD

**Issue by obvio171** [CollectionFS/Meteor-cfs-s3#30]
I want to store JSON files in a specific directory structure in the bucket. Sorry for the n00b question, just trying to figure out if cfs works for what I'm trying to do. Thanks for any help!

**Comment by szimmer1** [comment]
Old, but if useful to others, there is a folder property in the store settings object:

    storeSettings = {
    region: "us-west-2",
    secretAccessKey: awsSecretAccessKey,
    accessKeyId: awsAccessKeyId,
    bucket: awsBucket,
    folder: 'json'
    }

**Comment by aldeed** [comment]
You can also use `fileKeyMaker` function to customize the folders per file.
