### ISSUE TITLE
Getting an Error: Error storing file to the images store: null    

### ISSUE THREAD

**Issue by advany** [CollectionFS/Meteor-cfs-s3#47]
Made an simple site to test is... getting the same error...

Whats going wrong?

https://gist.github.com/advany/9ad16b180e2dea04574b

**Comment by fpoirier1** [comment]
Same thing here.

**Comment by fpoirier1** [comment]
`ACL: "public"` seems to the be the promblem..

**Comment by advany** [comment]
aaah... ill set it to private and see if it works! thnx

**Comment by aldeed** [comment]
Yep, there is not an ACL named "public". See "Canned ACLs" section here: http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html
