### ISSUE TITLE
Error storing file to the audioFile store: connect ETIMEDOUT

### ISSUE THREAD

**Issue by etmarch** [CollectionFS/Meteor-cfs-s3#48]
Can't for the life of me figure out why I'm having such a hard time storing files to my S3 buckets. The files are successfully stored in the database under 'cfs.audiofiles.filerecords' and 'cfs._tempstore', but I can never see them in my buckets. The error I am seeing is: ```W20150201-20:35:45.969(-5)? (STDERR) /Users/evanmarchand/Desktop/meteor/mk/insonic/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:3160
W20150201-20:35:45.970(-5)? (STDERR)       throw err;
W20150201-20:35:45.970(-5)? (STDERR)             ^
W20150201-20:35:45.970(-5)? (STDERR) Error: Error storing file to the audioFile store: connect ETIMEDOUT
W20150201-20:35:45.970(-5)? (STDERR)     at [object Object].<anonymous> (packages/cfs:collection/common.js:88:1)
W20150201-20:35:45.970(-5)? (STDERR)     at [object Object].emit (events.js:106:17)
W20150201-20:35:45.970(-5)? (STDERR)     at Writable.<anonymous> (packages/cfs:storage-adapter/storageAdapter.server.js:203:1)
W20150201-20:35:45.970(-5)? (STDERR)     at Writable.emit (events.js:117:20)
W20150201-20:35:45.970(-5)? (STDERR)     at Response.<anonymous> (packages/cfs:s3/s3.upload.stream2.js:178:1)
W20150201-20:35:45.970(-5)? (STDERR)     at Request.<anonymous> (/Users/evanmarchand/.meteor/packages/cfs_s3/.0.1.1.1s2h5n1++os+web.browser+web.cordova/npm/node_modules/aws-sdk/lib/request.js:350:18)
W20150201-20:35:45.970(-5)? (STDERR)     at Request.callListeners (/Users/evanmarchand/.meteor/packages/cfs_s3/.0.1.1.1s2h5n1++os+web.browser+web.cordova/npm/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
W20150201-20:35:45.970(-5)? (STDERR)     at Request.emit (/Users/evanmarchand/.meteor/packages/cfs_s3/.0.1.1.1s2h5n1++os+web.browser+web.cordova/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
W20150201-20:35:45.970(-5)? (STDERR)     at Request.emit (/Users/evanmarchand/.meteor/packages/cfs_s3/.0.1.1.1s2h5n1++os+web.browser+web.cordova/npm/node_modules/aws-sdk/lib/request.js:604:14)
W20150201-20:35:45.970(-5)? (STDERR)     at Request.transition (/Users/evanmarchand/.meteor/packages/cfs_s3/.0.1.1.1s2h5n1++os+web.browser+web.cordova/npm/node_modules/aws-sdk/lib/request.js:21:12)
=> Exited with code: 7
```
My policy that I attached to the user I created is: 

```{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:ListBucket"
      ],
      "Resource": "arn:aws:s3:::*"
    },
    {
      "Action": [
        "s3:PutObject",
        "s3:PutObjectAcl",
        "s3:GetObject",
        "s3:GetObjectAcl",
        "s3:DeleteObject",
        "s3:DeleteObjectAcl"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::avatars.small/*",
        "arn:aws:s3:::avatars.large/*",
        "arn:aws:s3:::insonic.audio/*",
"arn:aws:s3:::insonic.audio",
        "arn:aws:s3:::large.song.images/*",
        "arn:aws:s3:::small.song.images/*",
        "arn:aws:s3:::profile.cover.images/*"
      ]
    }
  ]
}
```
My Store code in /both/collections looks like : ```audioFileStore = new FS.Store.S3("audioFile", {
    region: "s3.amazonaws.com",
    accessKeyId: ****,
    secretAccessKey:*****,
    bucket: "insonic.audio",
    ACL: "public"
});```
Ive tried many combinations but nothing works. Any help is appreciated.

**Comment by etmarch** [comment]
Update: So apparently after I removed the region and bucket fields from the Fs.Store call, my meteor app finally started saving the files to bucket, and I am able to retrieve them with the normal Fs.File utilities. Now as I understand the way I am storing my keys is really really bad securities practices, but im not sure how to properly store them in my environment - a quick tutorial on that would be much appreciated.

**Comment by etmarch** [comment]
Another Update: I was wrong before, so the error I am seeing now is: ```Error: Error storing file to the audioFile store: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.``` 
I believe that this issue is related to file size, and I thought the last update to this package was supposed to fix the size issue, but maybe I am doing something wrong.

Not sure if this is related but I upload two files at the same time (on autoform submit) - an image and an audio/mp3 file. The image file appears basically immediately after uploading, meanwhile I cannot play the song file until I have manually refreshed my page. Hope that helps, I will continue looking into this myself as well.

**Comment by aldeed** [comment]
Same problem as https://github.com/CollectionFS/Meteor-cfs-s3/issues/47
